class MESSAGES:
    S_BACKUP_ALREADY_CREATED = "backup already created"
    S_MAKING_DIRECTORY = "creating directory"
    S_CREATING_BACKUP = "creating backup for"
    S_BACKUP_CREATED = "backup_created_successfully"
    S_MONGO_STARTING_BACKUP = "mongo creating backup"
    S_MONGO_STARTING_EXTENDED_BACKUP = "mongo creating extended backup"
    S_ELASTIC_STARTING_BACKUP = "elastic creating backup"
    S_ELASTIC_STARTING_EXTENDED_BACKUP = "elastic creating extended backup"
    S_CLEAN_BACKUP = "backup cleaned successfully"
