class APPICATION_CONTROLLER_COMMANDS:
    S_START_APPLICATION = 1
    S_CREATE_APPLICATION_STATUS = 2

class APPICATION_MODEL_COMMANDS:
    S_START_CRONJOB = 1
    S_CREATE_APPLICATION_STATUS = 2

class CRONJOB_COMMANDS_TIMER:
    S_INIT_DICTIONARY = 10
    S_CREATE_BACKUP = 10
